<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Age and sex distributions • nipnTK</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/sandstone/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Age and sex distributions">
<meta property="og:description" content="nipnTK">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-155098215-2"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-155098215-2');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">nipnTK</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/nipnTK.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/rl.html">Check ranges and legal values</a>
    </li>
    <li>
      <a href="../articles/sp.html">Identify outliers using scatterplots</a>
    </li>
    <li>
      <a href="../articles/flagging.html">Identify outliers using flags</a>
    </li>
    <li>
      <a href="../articles/ad.html">Assess distributions of variables and indices</a>
    </li>
    <li>
      <a href="../articles/dp.html">Assess digit preference</a>
    </li>
    <li>
      <a href="../articles/ah.html">Assess age heaping</a>
    </li>
    <li>
      <a href="../articles/sr.html">Assess sex ratio</a>
    </li>
    <li>
      <a href="../articles/as.html">Assess age and sex distributions</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/nutriverse/nipnTK/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="as_files/accessible-code-block-0.0.1/empty-anchor.js"></script><script src="as_files/kePrint-0.0.1/kePrint.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Age and sex distributions</h1>
                        <h4 class="author">Mark Myatt</h4>
            
      
      <small class="dont-index">Source: <a href="https://github.com/nutriverse/nipnTK/blob/master/vignettes/as.Rmd"><code>vignettes/as.Rmd</code></a></small>
      <div class="hidden name"><code>as.Rmd</code></div>

    </div>

    
    
<div id="age-and-sex-distributions-childrens-data" class="section level2">
<h2 class="hasAnchor">
<a href="#age-and-sex-distributions-childrens-data" class="anchor"></a>Age and sex distributions (children’s data)</h2>
<p>Age heaping is the tendency to report children’s ages to the nearest year or adult ages to the nearest multiple of 5 or 10 years. Age heaping is very common. It is a major reason why data from nutritional anthropometry surveys are often analysed and reported using broad age-groups. The commonest age-groups used with children’s data are 6 to 17 months, 18 to 29 months, 30 to 41 months, 42 to 53 months, and 54 to 59 months (see figure below). These are known as year-centred age-groups. Note that the last age-group covers only six months but is nominally centred at five years. Other age-groups may be used for specific analyses. The techniques presented here can be adapted to work with other age- groups.</p>
<p><img src="../man/figures/asFigure1.png" width="270" style="display: block; margin: auto;"></p>
<p>We will retrieve a survey dataset:</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="no">svy</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span>(<span class="st">"dp.ex02.csv"</span>, <span class="kw">header</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">sep</span> <span class="kw">=</span> <span class="st">","</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="no">svy</span>)</pre></body></html></div>
<pre><code>#&gt;   psu age sex weight height muac oedema
#&gt; 1   1   6   1    7.3   65.0  146      2
#&gt; 2   1  42   2   12.5   89.5  156      2
#&gt; 3   1  23   1   10.6   78.1  149      2
#&gt; 4   1  18   1   12.8   81.5  160      2
#&gt; 5   1  52   1   12.1   87.3  152      2
#&gt; 6   1  36   2   16.9   93.0  190      2</code></pre>
<p>The dataset <code>dp.ex02</code> is a comma-separated-value (CSV) file containing anthropometric data from a SMART survey in Kabul, Afghanistan.</p>
<div id="tabulation-and-visualisation" class="section level3">
<h3 class="hasAnchor">
<a href="#tabulation-and-visualisation" class="anchor"></a>Tabulation and visualisation</h3>
<p>The NiPN data quality toolkit provides an R language function called <code>recode()</code> that makes it easy to recode and group data. We will use the <code>recode()</code> function to group the data in the age variable (age in months) into year-centred age-groups.</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="no">svy</span>$<span class="no">ycag</span> <span class="kw">&lt;-</span> <span class="fu">recode</span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="st">"6:17=1; 18:29=2; 30:41=3; 42:53=4; 54:59=5"</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="no">svy</span>)
<span class="co">#&gt;   psu age sex weight height muac oedema ycag</span>
<span class="co">#&gt; 1   1   6   1    7.3   65.0  146      2    1</span>
<span class="co">#&gt; 2   1  42   2   12.5   89.5  156      2    4</span>
<span class="co">#&gt; 3   1  23   1   10.6   78.1  149      2    2</span>
<span class="co">#&gt; 4   1  18   1   12.8   81.5  160      2    2</span>
<span class="co">#&gt; 5   1  52   1   12.1   87.3  152      2    4</span>
<span class="co">#&gt; 6   1  36   2   16.9   93.0  190      2    3</span></pre></body></html></div>
<p>A tabular analysis can be performed:</p>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>)
<span class="co">#&gt;    </span>
<span class="co">#&gt;       1   2</span>
<span class="co">#&gt;   1 101 106</span>
<span class="co">#&gt;   2 102  96</span>
<span class="co">#&gt;   3 126 115</span>
<span class="co">#&gt;   4  78  82</span>
<span class="co">#&gt;   5  31  36</span>
<span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>)) * <span class="fl">100</span>
<span class="co">#&gt;    </span>
<span class="co">#&gt;             1         2</span>
<span class="co">#&gt;   1 11.569301 12.142039</span>
<span class="co">#&gt;   2 11.683849 10.996564</span>
<span class="co">#&gt;   3 14.432990 13.172967</span>
<span class="co">#&gt;   4  8.934708  9.392898</span>
<span class="co">#&gt;   5  3.550974  4.123711</span></pre></body></html></div>
<p>The <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> function performs a cross-tabulation. The first variable specified (<code>svy$ycag</code> in this example) is the row variable. The second variable specified (<code>svy$sex</code> in this example) is the column variable.</p>
<p><img src="../man/figures/asTable.png" width="390" style="display: block; margin: auto;"></p>
<p>It is useful to examine row percentages and column percentages in tables of age-group by sex. We should look at row percentages:</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>), <span class="kw">margin</span> <span class="kw">=</span> <span class="fl">1</span>) * <span class="fl">100</span></pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt;    
#&gt;            1        2
#&gt;   1 48.79227 51.20773
#&gt;   2 51.51515 48.48485
#&gt;   3 52.28216 47.71784
#&gt;   4 48.75000 51.25000
#&gt;   5 46.26866 53.73134</code></pre>
<p>Which shows approximately equal proportions of males and females in each year-centred age-group. We specified <code>margin = 1</code> with the <code><a href="https://rdrr.io/r/base/proportions.html">prop.table()</a></code> function because we wanted row percentages.</p>
<p>We should also look at column percentages:</p>
<div class="sourceCode" id="cb7"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>), <span class="kw">margin</span> <span class="kw">=</span> <span class="fl">2</span>) * <span class="fl">100</span></pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt;    
#&gt;             1         2
#&gt;   1 23.059361 24.367816
#&gt;   2 23.287671 22.068966
#&gt;   3 28.767123 26.436782
#&gt;   4 17.808219 18.850575
#&gt;   5  7.077626  8.275862</code></pre>
<p>We expect there to be approximately equal proportions of children in the age-groups centred at 1, 2, 3, and 4 years and a smaller proportion (i.e. about half that in the other age-groups) in the age-group centred at 5 years. We specified <code>margin = 2</code> with the <code><a href="https://rdrr.io/r/base/proportions.html">prop.table()</a></code> function because we wanted column percentages.</p>
<p>A graphical analysis using a population pyramid can be useful. The NiPN data quality toolkit provides an <em>R</em> language function called <code><a href="../reference/pyramid.plot.html">pyramid.plot()</a></code> for plotting population pyramids:</p>
<div class="sourceCode" id="cb9"><html><body><pre class="r"><span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as6-1.png" width="700" style="display: block; margin: auto;"></p>
<p>We can make a more informative plot by specifying a title and axis labels:</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Distribution of age by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Frequency (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Year-centred age-group"</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as6a-1.png" width="700" style="display: block; margin: auto;"></p>
<p>and applying shading:</p>
<div class="sourceCode" id="cb11"><html><body><pre class="r"><span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Distribution of age by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Frequency (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Year-centred age-group"</span>,
             <span class="kw">col</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"grey80"</span>, <span class="st">"white"</span>))</pre></body></html></div>
<p><img src="as_files/figure-html/as6b-1.png" width="700" style="display: block; margin: auto;"></p>
<p>or colours:</p>
<div class="sourceCode" id="cb12"><html><body><pre class="r"><span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Distribution of age by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Frequency (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Year-centred age-group"</span>,
             <span class="kw">col</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"lightblue"</span>, <span class="st">"pink"</span>))</pre></body></html></div>
<p><img src="as_files/figure-html/as6c-1.png" width="700" style="display: block; margin: auto;"></p>
<p>We expect there to be approximately equal numbers of children in the age-groups centred at 1, 2, 3, and 4 years and a smaller number (i.e. about half the number in the other age-groups) in the age-group centred at 5 years. There should also be approximately equal numbers of males and females. This is what we see in the population pyramid below.</p>
<div class="sourceCode" id="cb13"><html><body><pre class="r"><span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Distribution of age by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Frequency (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Year-centred age-group"</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as6d-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The <code><a href="../reference/pyramid.plot.html">pyramid.plot()</a></code> function uses the values of the grouped age variable as y-axis value labels.</p>
<p>We can assign descriptive text values using the <code>recode()</code> function. For example:</p>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="no">svy</span>$<span class="no">ageLabel</span> <span class="kw">&lt;-</span> <span class="fu">recode</span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="st">"6:29='&lt; 30 months'; 30:hi='30 month or older'"</span>)

<span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ageLabel</span>,
             <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Distribution of age by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Frequency (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Age-group"</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as7-1.png" width="700" style="display: block; margin: auto;"></p>
<p>We can also use a factor type variable. This type of variable allows labels to be specified:</p>
<div class="sourceCode" id="cb15"><html><body><pre class="r"><span class="no">svy</span>$<span class="no">ageLabel</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>,
                       <span class="kw">labels</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"6:17"</span>, <span class="st">"18:29"</span>, <span class="st">"30:41"</span>, <span class="st">"42:53"</span>, <span class="st">"54:59"</span>))

<span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ageLabel</span>,
             <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Distribution of age by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Frequency (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Year-centred age-group"</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as7a-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The <code><a href="https://rdrr.io/r/base/cut.html">cut()</a></code> function may also be used:</p>
<div class="sourceCode" id="cb16"><html><body><pre class="r"><span class="no">svy</span>$<span class="no">ageCuts</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="kw">breaks</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>, <span class="fl">17</span>, <span class="fl">29</span>, <span class="fl">41</span>, <span class="fl">53</span>, <span class="fl">59</span>))

<span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ageCuts</span>,
             <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Age-group (months) "</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Frequency (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Year-centred age-group"</span>,
             <span class="kw">cex.names</span> <span class="kw">=</span> <span class="fl">0.9</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as7b-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The <code><a href="https://rdrr.io/r/base/cut.html">cut()</a></code> function is a versatile grouping function. It is explained in more detail later in this section.</p>
<p>The <code>cex.names</code> parameter of the <code><a href="../reference/pyramid.plot.html">pyramid.plot()</a></code> function allows us to change the size of the value labels on the <code>y-axis</code>. The value for cex.names is a magnification factor. Values above one make the labels larger than the default. Values below one make the labels smaller than the default.</p>
</div>
</div>
<div id="simple-testing" class="section level2">
<h2 class="hasAnchor">
<a href="#simple-testing" class="anchor"></a>Simple testing</h2>
<p>It is possible to perform a formal test on the distribution of age-groups by sex. A simple test is:</p>
<div class="sourceCode" id="cb17"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>, <span class="no">svy</span>$<span class="no">sex</span>))</pre></body></html></div>
<p>This yields:</p>
<pre><code>#&gt; 
#&gt;  Pearson's Chi-squared test
#&gt; 
#&gt; data:  table(svy$ycag, svy$sex)
#&gt; X-squared = 1.2675, df = 4, p-value = 0.8669</code></pre>
<p>In this example the p-value is not below 0.05 so we accept the null hypothesis that there is no significant association between age and sex. This is an important test as it tests whether the distribution of ages is similar for males and females. It does not, however, test whether the age structure in the sample meets expectations. This requires a test that compares observed numbers with expected numbers derived from an external source (e.g. census data) or from a demographic model.</p>
<div id="a-model-of-the-expected-age-structure" class="section level3">
<h3 class="hasAnchor">
<a href="#a-model-of-the-expected-age-structure" class="anchor"></a>A model of the expected age structure</h3>
<p>A simple model-based method for calculating expected numbers is exponential decay in a population in which births and deaths balance each other and with a 1:1 male to female sex ratio. Under this model the proportion surviving in each group at each year can be calculated as:</p>
<p><span class="math display">\[ p ~ = ~ e ^ {-zt} \]</span></p>
<p>in which e is the base of the natural logarithm (approximately 2.7183), z is the mortality rate associated with each time period, and t is time. Time (t) starts at zero for the purposes of computation. Age can be used as a measure of time since birth. We should use 0 for the first year-centred age-group, 1 for the second year-centred age-group, and so-on. This is the rationale for us using <code>t &lt;- 0:4</code> below.</p>
<p>With five year-centred age-groups and a mortality rate of 1 / 10,000 / day, the expected proportions surviving at each year can be calculated as:</p>
<div class="sourceCode" id="cb19"><html><body><pre class="r"><span class="no">z</span> <span class="kw">&lt;-</span> (<span class="fl">1</span> / <span class="fl">10000</span>) * <span class="fl">365.25</span>

<span class="no">t</span> <span class="kw">&lt;-</span> <span class="fl">0</span>:<span class="fl">4</span>

<span class="no">p</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span>(-<span class="no">z</span> * <span class="no">t</span>)

<span class="no">p</span></pre></body></html></div>
<p>This yields the following survival probabilities:</p>
<div class="sourceCode" id="cb20"><html><body><pre class="r"><span class="no">z</span> <span class="kw">&lt;-</span> (<span class="fl">1</span> / <span class="fl">10000</span>) * <span class="fl">365.25</span>

<span class="no">t</span> <span class="kw">&lt;-</span> <span class="fl">0</span>:<span class="fl">4</span>

<span class="no">p</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span>(-<span class="no">z</span> * <span class="no">t</span>)

<span class="no">p</span>
<span class="co">#&gt; [1] 1.0000000 0.9641340 0.9295544 0.8962149 0.8640713</span></pre></body></html></div>
<p>We need to specify the duration (i.e. the number of years) represented by each age-group:</p>
<div class="sourceCode" id="cb21"><html><body><pre class="r"><span class="no">d</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">1</span>, <span class="fl">0.5</span>)</pre></body></html></div>
<p>We can then calculate expected proportions of children in each age-group:</p>
<div class="sourceCode" id="cb22"><html><body><pre class="r"><span class="no">ep</span> <span class="kw">&lt;-</span> <span class="no">d</span> * <span class="no">p</span> / <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">d</span> * <span class="no">p</span>)

<span class="no">ep</span></pre></body></html></div>
<p>This gives:</p>
<pre><code>#&gt; [1] 0.2368580 0.2283628 0.2201724 0.2122757 0.1023311</code></pre>
<p>We can now calculate expected numbers:</p>
<div class="sourceCode" id="cb24"><html><body><pre class="r">expected &lt;- ep * sum(table(svy$ycag)) names(expected) &lt;- 1:5

expected</pre></body></html></div>
<p>giving:</p>
<pre><code>#&gt;         1         2         3         4         5 
#&gt; 206.77703 199.36076 192.21049 185.31667  89.33505</code></pre>
<p>A formal test would compare the observed numbers with the expected numbers. The observed numbers can be found using:</p>
<div class="sourceCode" id="cb26"><html><body><pre class="r"><span class="no">observed</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ycag</span>)

<span class="no">observed</span></pre></body></html></div>
<p>This gives:</p>
<pre><code>#&gt; 
#&gt;   1   2   3   4   5 
#&gt; 207 198 241 160  67</code></pre>
<p>It can be useful to examine observed and expected numbers graphically:</p>
<div class="sourceCode" id="cb28"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="kw">mfcol</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>, <span class="fl">2</span>))
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="no">observed</span>, <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Observed"</span>, <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Age group"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Frequency"</span>, <span class="kw">ylim</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>, <span class="fl">250</span>))
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="no">expected</span>, <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Expected"</span>, <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Age group"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Frequency"</span>, <span class="kw">ylim</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>, <span class="fl">250</span>))</pre></body></html></div>
<p><img src="as_files/figure-html/as9i-1.png" width="700" style="display: block; margin: auto;"></p>
<p>We will calculate a Chi-squared test statistic:</p>
<p><span class="math display">\[ \chi ^ 2 ~ = ~ \sum \frac{(\text{observed} - \text{expected}) ^ 2}{\text{expected}} \]</span></p>
<p>using:</p>
<div class="sourceCode" id="cb29"><html><body><pre class="r"><span class="no">X2</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>((<span class="no">observed</span> - <span class="no">expected</span>) ^ <span class="fl">2</span> / <span class="no">expected</span>)</pre></body></html></div>
<p>which yields a Chi-Squared test statistic of:</p>
<p>We can find the p-value using:</p>
<div class="sourceCode" id="cb30"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span>(<span class="no">X2</span>, <span class="kw">df</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">lower.tail</span> <span class="kw">=</span> <span class="fl">FALSE</span>)</pre></body></html></div>
<p>This gives:</p>
<pre><code>#&gt; [1] 0.000259395</code></pre>
<p>In this example the age distribution is significantly different from expected numbers calculated using a simple demographic model.</p>
<p>Note that we specify the degrees of freedom (<code>df</code>) for the Chi-Squared test as the number of age-groups minus one. As we have five age-groups we specify <code>df = 4</code>. The degrees of freedom (<code>df</code>) that we need to specify will depend on the number of age-groups that we use. It is always the number of age-groups minus one. If, for example, there are ten age-groups we would need to specify <code>df = 9</code>.</p>
<p>The NiPN data quality toolkit provides an R function called <code><a href="../reference/ageChildren.html">ageChildren()</a></code> that performs the model- based Chi-Squared test:</p>
<div class="sourceCode" id="cb32"><html><body><pre class="r"><span class="fu"><a href="../reference/ageChildren.html">ageChildren</a></span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="kw">u5mr</span> <span class="kw">=</span> <span class="fl">1</span>)</pre></body></html></div>
<p>which returns:</p>
<pre><code>#&gt; 
#&gt;  Age Test (Children)
#&gt; 
#&gt; X-squared = 21.4366, df = 4, p = 0.0003</code></pre>
<p>Note that we specified the under five years mortality rate as 1 / 10,000 / day using <code>u5mr = 1</code>. Another, more appropriate, rate may be specified.</p>
<p>The <code><a href="../reference/ageChildren.html">ageChildren()</a></code> function calculates year-centred age-groups for children aged between six and fifty-nine months by default. This is a standard survey population and is used in SMART and many other surveys. The use of year-centred age-groups is also standard practice. The commands that are given above can, however, be adapted for use with different age-groups.</p>
<p>The output of the <code><a href="../reference/ageChildren.html">ageChildren()</a></code> function can be saved for later use:</p>
<div class="sourceCode" id="cb34"><html><body><pre class="r"><span class="no">ac</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/ageChildren.html">ageChildren</a></span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="kw">u5mr</span> <span class="kw">=</span> <span class="fl">1</span>)</pre></body></html></div>
<p>The saved output contains the Chi-squared test results and tables of observed and expected values. These can be accessed using:</p>
<div class="sourceCode" id="cb35"><html><body><pre class="r"><span class="no">ac</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;  Age Test (Children)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; X-squared = 21.4366, df = 4, p = 0.0003</span>

<span class="no">ac</span>$<span class="no">X2</span>
<span class="co">#&gt; [1] 21.43662</span>

<span class="no">ac</span>$<span class="no">df</span>
<span class="co">#&gt; [1] 4</span>

<span class="no">ac</span>$<span class="no">p</span>
<span class="co">#&gt; [1] 0.000259395</span>

<span class="no">ac</span>$<span class="no">observed</span>
<span class="co">#&gt;   1   2   3   4   5 </span>
<span class="co">#&gt; 207 198 241 160  67</span>

<span class="no">ac</span>$<span class="no">expected</span>
<span class="co">#&gt;         1         2         3         4         5 </span>
<span class="co">#&gt; 206.77703 199.36076 192.21049 185.31667  89.33505</span></pre></body></html></div>
<p>The saved results may also be plotted:</p>
<div class="sourceCode" id="cb36"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="no">ac</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as10d-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The <code><a href="../reference/ageChildren.html">ageChildren()</a></code> function can be applied to each sex separately. To males:</p>
<div class="sourceCode" id="cb37"><html><body><pre class="r"><span class="no">acM</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/ageChildren.html">ageChildren</a></span>(<span class="no">svy</span>$<span class="no">age</span>[<span class="no">svy</span>$<span class="no">sex</span> <span class="kw">==</span> <span class="fl">1</span>], <span class="kw">u5mr</span> <span class="kw">=</span> <span class="fl">1</span>)

<span class="no">acM</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;  Age Test (Children)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; X-squared = 15.8496, df = 4, p = 0.0032</span>

<span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="no">acM</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as11-1.png" width="700" style="display: block; margin: auto;"></p>
<p>and to females:</p>
<div class="sourceCode" id="cb38"><html><body><pre class="r"><span class="no">acF</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/ageChildren.html">ageChildren</a></span>(<span class="no">svy</span>$<span class="no">age</span>[<span class="no">svy</span>$<span class="no">sex</span> <span class="kw">==</span> <span class="fl">2</span>], <span class="kw">u5mr</span> <span class="kw">=</span> <span class="fl">1</span>)

<span class="no">acF</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;  Age Test (Children)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; X-squared = 6.8429, df = 4, p = 0.1444</span>

<span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="no">acF</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as12-1.png" width="700" style="display: block; margin: auto;"></p>
<p>An easier way of doing this is:</p>
<div class="sourceCode" id="cb39"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/by.html">by</a></span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="no">svy</span>$<span class="no">sex</span>, <span class="no">ageChildren</span>, <span class="kw">u5mr</span> <span class="kw">=</span> <span class="fl">1</span>)
<span class="co">#&gt; svy$sex: 1</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;  Age Test (Children)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; X-squared = 15.8496, df = 4, p = 0.0032</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; ------------------------------------------------------------ </span>
<span class="co">#&gt; svy$sex: 2</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;  Age Test (Children)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; X-squared = 6.8429, df = 4, p = 0.1444</span></pre></body></html></div>
<p>The test statistics should be interpreted with caution. A significant test result may, for example, be due to the use of an inappropriate model to generate expected numbers.</p>
<p>A significant result in this particular test may be due to:</p>
<ul>
<li><p><strong>Specifying an inappropriate under five years mortality rate:</strong> This is a particular problem because the specified under five years mortality rate is assumed to have applied for five years prior to data being collected.</p></li>
<li><p><strong>The assumption of a 1:1 male to female sex ratio:</strong> This is a particular problem in setting in which there is sex-selective abortion and sex-selective infanticide.</p></li>
</ul>
<p>The model is crude. Mortality is related to age. Younger children have a greater mortality risk than older children and only an average under five years mortality rate is used. A more sophisticated model could be used but, in many settings, we will not have the data required to use such a model.</p>
<p>It should also be noted that the sample sizes used in most survey can cause tests to yield statistically significant results for small differences between observed and expected numbers.</p>
</div>
</div>
<div id="use-of-census-data" class="section level2">
<h2 class="hasAnchor">
<a href="#use-of-census-data" class="anchor"></a>Use of census data</h2>
<p>The use of simple demographic models is far from ideal. It is usually better to calculate the expected proportions from census data. A useful source of census data is the <a href="https://www.census.gov/data-tools/demo/idb/informationGateway.php">United States Census Bureau’s International Data Base</a>:</p>
<p><a href="https://www.census.gov/data-tools/demo/idb/informationGateway.php" class="uri">https://www.census.gov/data-tools/demo/idb/informationGateway.php</a></p>
<p>The population in single year age-groups for 0, 1, 2, 3, and 4 years for Afghanistan in 2015 was:</p>
<table class="table table table-striped">
<thead><tr>
<th style="text-align:right;">
Age
</th>
<th style="text-align:right;">
Both Sexes
</th>
<th style="text-align:right;">
Males
</th>
<th style="text-align:right;">
Females
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1148379
</td>
<td style="text-align:right;">
584276
</td>
<td style="text-align:right;">
564103
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1062635
</td>
<td style="text-align:right;">
539589
</td>
<td style="text-align:right;">
523046
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1015688
</td>
<td style="text-align:right;">
515793
</td>
<td style="text-align:right;">
499895
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
981288
</td>
<td style="text-align:right;">
498365
</td>
<td style="text-align:right;">
482923
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
950875
</td>
<td style="text-align:right;">
482926
</td>
<td style="text-align:right;">
467949
</td>
</tr>
</tbody>
</table>
<p>We can calculate expected values from these data:</p>
<div class="sourceCode" id="cb40"><html><body><pre class="r"><span class="no">pop</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1148379</span>, <span class="fl">1062635</span>, <span class="fl">1015688</span>, <span class="fl">981288</span>, <span class="fl">950875</span>)
<span class="no">ep</span> <span class="kw">&lt;-</span> <span class="no">pop</span> / <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">pop</span>)</pre></body></html></div>
<p>With a sample size of <span class="math inline">\(n = 900\)</span> the expected number in each age-group would be:</p>
<div class="sourceCode" id="cb41"><html><body><pre class="r"><span class="no">expected</span> <span class="kw">&lt;-</span> <span class="no">ep</span> * <span class="fl">900</span>
<span class="no">expected</span>
<span class="co">#&gt; [1] 200.3427 185.3841 177.1939 171.1925 165.8868</span></pre></body></html></div>
<p>These expected values can be used in a Chi-squared test as is illustrated above.</p>
<p>Census data may also be used to estimate the under five years’ mortality rate (U5MR) which can then be used with the <code><a href="../reference/ageChildren.html">ageChildren()</a></code> function.</p>
<p>The model of exponential decay in a population in which births and deaths balance each other with a 1:1 male to female sex ratio:</p>
<p><span class="math display">\[ p ~ = ~ e ^ {-zt} \]</span></p>
<p>means that we can, given an age-distribution, estimate mortality by fitting the model:</p>
<p><span class="math display">\[ \log_e(n) ~ = ~ \alpha ~ + ~ \beta t \]</span></p>
<p>where <span class="math inline">\(n\)</span> is the count of children in each age-group.</p>
<p>The absolute value of the β coefficient is the point estimate of the mortality rate (z). Using the 2015 population data for Afghanistan:</p>
<div class="sourceCode" id="cb42"><html><body><pre class="r"><span class="no">t</span> <span class="kw">&lt;-</span> <span class="fl">0</span>:<span class="fl">4</span>
<span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span>(<span class="no">pop</span>) ~ <span class="no">t</span>)</pre></body></html></div>
<p>This gives:</p>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = log(pop) ~ t)
#&gt; 
#&gt; Coefficients:
#&gt; (Intercept)            t  
#&gt;    13.93601     -0.04571</code></pre>
<p>The value reported under <strong>t</strong> is the <span class="math inline">\(\beta\)</span> coefficient (<strong>-0.04571</strong>). The absolute value of the <span class="math inline">\(\beta\)</span> coefficient (i.e. the value without the sign) is <strong>0.04571</strong>. This is the point estimate of the mortality rate. Expressed as the number of deaths / 10,000 persons / day:</p>
<div class="sourceCode" id="cb44"><html><body><pre class="r">(<span class="fl">0.04571</span> / <span class="fl">365.25</span>) * <span class="fl">10000</span></pre></body></html></div>
<p>this is:</p>
<pre><code>#&gt; [1] 1.251472</code></pre>
<p>We can use this estimate with the <code><a href="../reference/ageChildren.html">ageChildren()</a></code> function:</p>
<div class="sourceCode" id="cb46"><html><body><pre class="r"><span class="fu"><a href="../reference/ageChildren.html">ageChildren</a></span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="kw">u5mr</span> <span class="kw">=</span> <span class="fl">1.251472</span>)
<span class="co">#&gt; </span>
<span class="co">#&gt;  Age Test (Children)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; X-squared = 20.4744, df = 4, p = 0.0004</span></pre></body></html></div>
<div id="the-age-ratio" class="section level3">
<h3 class="hasAnchor">
<a href="#the-age-ratio" class="anchor"></a>The age ratio</h3>
<p>A much simpler and less problematic age-related test of survey and data quality is the <em>age ratio</em> test.</p>
<p>The age ratio is defined as:</p>
<p><span class="math display">\[ \text{Age ratio} ~ = ~ \frac{\text{number of children aged between 6 and 29 months}}{\text{number of children aged between 30 and 59 months}} \]</span></p>
<p>We will use the <code>recode()</code> function from NiPN data quality toolkit to create the relevant age-groups:</p>
<div class="sourceCode" id="cb47"><html><body><pre class="r"><span class="no">svy</span>$<span class="no">ageGroup</span> <span class="kw">&lt;-</span> <span class="fu">recode</span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="st">"6:29=1; 30:59=2"</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="no">svy</span>)
<span class="co">#&gt;   psu age sex weight height muac oedema ycag ageLabel ageCuts ageGroup</span>
<span class="co">#&gt; 1   1   6   1    7.3   65.0  146      2    1     6:17  (0,17]        1</span>
<span class="co">#&gt; 2   1  42   2   12.5   89.5  156      2    4    42:53 (41,53]        2</span>
<span class="co">#&gt; 3   1  23   1   10.6   78.1  149      2    2    18:29 (17,29]        1</span>
<span class="co">#&gt; 4   1  18   1   12.8   81.5  160      2    2    18:29 (17,29]        1</span>
<span class="co">#&gt; 5   1  52   1   12.1   87.3  152      2    4    42:53 (41,53]        2</span>
<span class="co">#&gt; 6   1  36   2   16.9   93.0  190      2    3    30:41 (29,41]        2</span></pre></body></html></div>
<p>The observed age ratio is:</p>
<div class="sourceCode" id="cb48"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span> <span class="kw">==</span> <span class="fl">1</span>) / <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span> <span class="kw">==</span> <span class="fl">2</span>)</pre></body></html></div>
<p>which gives:</p>
<pre><code>#&gt; [1] 0.8653846</code></pre>
<p>It is often easier to work with proportions than with ratios so we only need to calculate the proportion in the younger age-group:</p>
<div class="sourceCode" id="cb50"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span> <span class="kw">==</span> <span class="fl">1</span>) / <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>))</pre></body></html></div>
<p>which gives:</p>
<pre><code>#&gt; [1] 0.4639175</code></pre>
<p>We can calculate an expected value using census data or a simple demographic model. The simplest approach is to use a standard value. SMART surveys often use the ratio 0.85:1.</p>
<p>We only need to calculate the expected proportion in the younger group. For the ratio 0.85:1 this is:</p>
<div class="sourceCode" id="cb52"><html><body><pre class="r"><span class="no">p</span> <span class="kw">&lt;-</span> <span class="fl">0.85</span> / (<span class="fl">0.85</span> + <span class="fl">1</span>)</pre></body></html></div>
<p>This gives:</p>
<pre><code>#&gt; [1] 0.4594595</code></pre>
<p>The observed proportion (0.4639175) and expected proportion (0.4594595) are so similar that a formal test of statistical significance is not required in this case.</p>
<p>Formal testing can be done using a Chi-squared test:</p>
<div class="sourceCode" id="cb54"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/prop.test.html">prop.test</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span> <span class="kw">==</span> <span class="fl">1</span>), <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>)), <span class="kw">p</span> <span class="kw">=</span> <span class="fl">0.4594595</span>)</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt; 
#&gt;  1-sample proportions test with continuity correction
#&gt; 
#&gt; data:  sum(svy$ageGroup == 1) out of sum(table(svy$ageGroup)), null probability 0.4594595
#&gt; X-squared = 0.053062, df = 1, p-value = 0.8178
#&gt; alternative hypothesis: true p is not equal to 0.4594595
#&gt; 95 percent confidence interval:
#&gt;  0.4304994 0.4976573
#&gt; sample estimates:
#&gt;         p 
#&gt; 0.4639175</code></pre>
<p>The age ratio in the example data is not significantly different from the expected age ratio.</p>
<p>The NiPN data quality toolkit provide an R function called <code><a href="../reference/ageRatioTest.html">ageRatioTest()</a></code> that performs the age ratio test:</p>
<div class="sourceCode" id="cb56"><html><body><pre class="r"><span class="fu"><a href="../reference/ageRatioTest.html">ageRatioTest</a></span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="kw">ratio</span> <span class="kw">=</span> <span class="fl">0.85</span>)</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt; 
#&gt;      Age Ratio Test (children's data)
#&gt; 
#&gt;                     Expected age ratio = 0.8500
#&gt; Expected proportion aged 6 - 29 months = 0.4595
#&gt; 
#&gt;                     Observed age ratio = 0.8654
#&gt; Observed proportion aged 6 - 29 months = 0.4639
#&gt; 
#&gt; X-squared = 0.0531, p = 0.8178</code></pre>
<p>The <code>ratio</code> parameter of the <code><a href="../reference/ageRatioTest.html">ageRatioTest()</a></code> function allows you to specify an expected age ratio other than 0.85:1.</p>
<p>Note that the <code><a href="../reference/ageRatioTest.html">ageRatioTest()</a></code> function applies the test to data from children aged between 6 and 59 months only (all other ages are ignored).</p>
<p>The age ratio test might be applied to data from both sexes (as above) and to each sex separately:</p>
<div class="sourceCode" id="cb58"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/by.html">by</a></span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="no">svy</span>$<span class="no">sex</span>, <span class="no">ageRatioTest</span>, <span class="kw">ratio</span> <span class="kw">=</span> <span class="fl">0.85</span>)
<span class="co">#&gt; svy$sex: 1</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;      Age Ratio Test (children's data)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;                     Expected age ratio = 0.8500</span>
<span class="co">#&gt; Expected proportion aged 6 - 29 months = 0.4595</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;                     Observed age ratio = 0.8638</span>
<span class="co">#&gt; Observed proportion aged 6 - 29 months = 0.4635</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; X-squared = 0.0145, p = 0.9041</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; ------------------------------------------------------------ </span>
<span class="co">#&gt; svy$sex: 2</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;      Age Ratio Test (children's data)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;                     Expected age ratio = 0.8500</span>
<span class="co">#&gt; Expected proportion aged 6 - 29 months = 0.4595</span>
<span class="co">#&gt; </span>
<span class="co">#&gt;                     Observed age ratio = 0.8670</span>
<span class="co">#&gt; Observed proportion aged 6 - 29 months = 0.4644</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; X-squared = 0.0247, p = 0.8750</span></pre></body></html></div>
<p>The example data meets expectations regarding the age ratio for all children and for male and female children separately.</p>
</div>
</div>
<div id="age-and-sex-distributions-adults-and-general-population-surveys" class="section level2">
<h2 class="hasAnchor">
<a href="#age-and-sex-distributions-adults-and-general-population-surveys" class="anchor"></a>Age and sex distributions : Adults and general population surveys</h2>
<p>A key test of survey quality is whether the survey data represents the population in terms of the age and sex distribution. We can test this by comparison with census data.</p>
<p>We will retrieve some example data:</p>
<div class="sourceCode" id="cb59"><html><body><pre class="r"><span class="no">svy</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span>(<span class="st">"as.ex01.csv"</span>, <span class="kw">header</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">sep</span> <span class="kw">=</span> <span class="st">","</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="no">svy</span>)</pre></body></html></div>
<pre><code>#&gt;   age sex
#&gt; 1  44   2
#&gt; 2   1   2
#&gt; 3  15   2
#&gt; 4   7   1
#&gt; 5  14   1
#&gt; 6  14   1</code></pre>
<p>These data are taken from household rosters collected as part of a household survey in Tanzania. We will use census data taken from the Wolfram|Alpha knowledge engine:</p>
<p><a href="http://www.wolframalpha.com/input/?i=Tanzania+age+distribution" class="uri">http://www.wolframalpha.com/input/?i=Tanzania+age+distribution</a></p>
<p>Another useful source of census data is the United States Census Bureau’s International Data Base:</p>
<p><a href="https://www.census.gov/data-tools/demo/idb/informationGateway.php" class="uri">https://www.census.gov/data-tools/demo/idb/informationGateway.php</a></p>
<p>The pyramid plot produced by Wolfram|Alpha is shown in the figure below.</p>
<p><img src="../man/figures/pyramidPlot.png" width="481" style="display: block; margin: auto;"></p>
<p>The table produced by Wolfram|Alpha was downloaded and stored in a CSV file:</p>
<div class="sourceCode" id="cb61"><html><body><pre class="r"><span class="no">ref</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span>(<span class="st">"as.ex02.csv"</span>, <span class="kw">header</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">sep</span> <span class="kw">=</span> <span class="st">","</span>)
<span class="no">ref</span></pre></body></html></div>
<pre><code>#&gt;         age   Males Females     All
#&gt; 1     [0,5) 4043000 3969000 8012000
#&gt; 2    [5,10) 3336000 3284000 6620000
#&gt; 3   [10,15) 2775000 2742000 5517000
#&gt; 4   [15,20) 2386000 2372000 4758000
#&gt; 5   [20,25) 2076000 2073000 4149000
#&gt; 6   [25,30) 1753000 1750000 3503000
#&gt; 7   [30,35) 1453000 1432000 2885000
#&gt; 8   [35,40) 1142000 1099000 2241000
#&gt; 9   [40,45)  873000  846000 1719000
#&gt; 10  [45,50)  673000  699000 1372000
#&gt; 11  [50,55)  538000  601000 1139000
#&gt; 12  [55,60)  433000  503000  936000
#&gt; 13  [60,65)  357000  426000  783000
#&gt; 14  [65,70)  266000  319000  585000
#&gt; 15  [70,75)  182000  222000  404000
#&gt; 16  [75,80)  108000  137000  245000
#&gt; 17  [80,85)   51000   68000  119000
#&gt; 18  [85,90)   17000   25000   42000
#&gt; 19  [90,95)    3000    6000    9000
#&gt; 20 [95,100)       0    1000    1000</code></pre>
<p>The age-groups are expressed using the form specified in ISO 31-11, an international standard that applies to mathematical symbols. The form [a,b) expresses the interval <span class="math inline">\(a ≤ x &lt; b\)</span>. For example, [30,35) is used to indicate the set {30, 31, 32, 33, 34} of ages in years. The form [a,b) is said to be <em>closed</em> on the left and <em>open</em> on the right.</p>
<p>The reference data (<code>ref</code>) uses five-year age-groups. We will create the same age-groups in the example dataset.</p>
<p>We should first check the range of ages in the example data:</p>
<div class="sourceCode" id="cb63"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/range.html">range</a></span>(<span class="no">svy</span>$<span class="no">age</span>)</pre></body></html></div>
<p>which returns:</p>
<pre><code>#&gt; [1]  0 93</code></pre>
<p>The R language provides a function that makes it easy to create ISO 31-11 groupings from raw data:</p>
<div class="sourceCode" id="cb65"><html><body><pre class="r"><span class="no">svy</span>$<span class="no">ageGroup</span> <span class="kw">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span>(<span class="no">svy</span>$<span class="no">age</span>,
                   <span class="kw">breaks</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="kw">from</span> <span class="kw">=</span> <span class="fl">0</span>, <span class="kw">to</span> <span class="kw">=</span> <span class="fl">95</span>, <span class="kw">by</span> <span class="kw">=</span> <span class="fl">5</span>),
                   <span class="kw">include.lowest</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">right</span> <span class="kw">=</span> <span class="fl">FALSE</span>)</pre></body></html></div>
<p>Using <code>include.lowest = TRUE</code> tells the <code><a href="https://rdrr.io/r/base/cut.html">cut()</a></code> function to include the lowest breaks value (zero in this case). Using <code>right = FALSE</code> tells the <code><a href="https://rdrr.io/r/base/cut.html">cut()</a></code> function to use groupings that are closed on the left. This combination of parameters creates the same “closed on the left” and “open on the right” age-groups as are used in the reference (<strong>ref</strong>) data:</p>
<div class="sourceCode" id="cb66"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>)
<span class="co">#&gt; </span>
<span class="co">#&gt;   [0,5)  [5,10) [10,15) [15,20) [20,25) [25,30) [30,35) [35,40) [40,45) [45,50) </span>
<span class="co">#&gt;    1598    1268    1072     808     870     575     580     385     424     258 </span>
<span class="co">#&gt; [50,55) [55,60) [60,65) [65,70) [70,75) [75,80) [80,85) [85,90) [90,95] </span>
<span class="co">#&gt;     284     128     165      82      98      51      60      18      12</span></pre></body></html></div>
<p>A tabular analysis of age-group by sex can be produced using:</p>
<div class="sourceCode" id="cb67"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>, <span class="no">svy</span>$<span class="no">sex</span>)
<span class="co">#&gt;          </span>
<span class="co">#&gt;             1   2</span>
<span class="co">#&gt;   [0,5)   821 777</span>
<span class="co">#&gt;   [5,10)  637 631</span>
<span class="co">#&gt;   [10,15) 547 525</span>
<span class="co">#&gt;   [15,20) 389 419</span>
<span class="co">#&gt;   [20,25) 342 528</span>
<span class="co">#&gt;   [25,30) 343 232</span>
<span class="co">#&gt;   [30,35) 250 330</span>
<span class="co">#&gt;   [35,40) 177 208</span>
<span class="co">#&gt;   [40,45) 206 218</span>
<span class="co">#&gt;   [45,50) 125 133</span>
<span class="co">#&gt;   [50,55) 162 122</span>
<span class="co">#&gt;   [55,60)  70  58</span>
<span class="co">#&gt;   [60,65)  87  78</span>
<span class="co">#&gt;   [65,70)  33  49</span>
<span class="co">#&gt;   [70,75)  47  51</span>
<span class="co">#&gt;   [75,80)  22  29</span>
<span class="co">#&gt;   [80,85)  24  36</span>
<span class="co">#&gt;   [85,90)  10   8</span>
<span class="co">#&gt;   [90,95]   1  11</span></pre></body></html></div>
<p>A visual inspection is useful:</p>
<div class="sourceCode" id="cb68"><html><body><pre class="r"><span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>, <span class="no">svy</span>$<span class="no">sex</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as35-1.png" width="700" style="display: block; margin: auto;"></p>
<p>We can make this easier to read:</p>
<div class="sourceCode" id="cb69"><html><body><pre class="r"><span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>,
             <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Age-group by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Number (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">""</span>,
             <span class="kw">las</span> <span class="kw">=</span> <span class="fl">1</span>,
             <span class="kw">cex.names</span> <span class="kw">=</span> <span class="fl">0.9</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as35a-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Note that we specified <code>ylab = ""</code> because it is clear that the category labels represent age-groups and to prevent the y-axis label from obscuring the category labels, which happens with:</p>
<div class="sourceCode" id="cb70"><html><body><pre class="r"><span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>,
             <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Age-group by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Number (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Age-group"</span>,
             <span class="kw">las</span> <span class="kw">=</span> <span class="fl">1</span>,
             <span class="kw">cex.names</span> <span class="kw">=</span> <span class="fl">0.9</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as35b-1.png" width="700" style="display: block; margin: auto;"></p>
<p>It is possible to alter the number of lines of text in margins of the plot, reduce the size of the age-group labels, and place the y-axis label on a specific line in the left margin of the plot in order to make a clearer plot:</p>
<div class="sourceCode" id="cb71"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="kw">mar</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">5</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">2</span>))

<span class="fu"><a href="../reference/pyramid.plot.html">pyramid.plot</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>,
             <span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Age-group by sex"</span>,
             <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Number (Males | Females)"</span>,
             <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">""</span>,
             <span class="kw">las</span> <span class="kw">=</span> <span class="fl">1</span>,
             <span class="kw">cex.names</span> <span class="kw">=</span> <span class="fl">0.8</span>)

<span class="fu"><a href="https://rdrr.io/r/graphics/title.html">title</a></span>(<span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Age-group"</span>, <span class="kw">line</span> <span class="kw">=</span> <span class="fl">4</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as35c-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The easiest way of checking whether the survey data represents the general population in terms of the age and sex distribution is to compare the observed (figure on right) and expected (figure on left) distributions.</p>
<p><img src="../man/figures/pyramidPlot.png" width="50%"><img src="as_files/figure-html/as35d-2.png" width="50%"></p>
<p>The general shapes of the two distributions are similar. Some of the lumpiness in figure on the right is due to age heaping in the adult ages at decades and half-decades:</p>
<div class="sourceCode" id="cb72"><html><body><pre class="r"><span class="no">ah</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/ageHeaping.html">ageHeaping</a></span>(<span class="no">svy</span>$<span class="no">age</span>, <span class="kw">divisor</span> <span class="kw">=</span> <span class="fl">10</span>)
<span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="no">ah</span>, <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Remainder of age / 10"</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as36-1.png" width="700"></p>
<p>A more formal test of the age structure can be made by comparing observed and expected numbers. We can do this graphically:</p>
<div class="sourceCode" id="cb73"><html><body><pre class="r"><span class="no">ref</span> <span class="kw">&lt;-</span> <span class="no">ref</span>[<span class="fl">1</span>:<span class="fl">19</span>, ]

<span class="no">expectedProportions</span> <span class="kw">&lt;-</span> <span class="no">ref</span>$<span class="no">All</span> / <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">ref</span>$<span class="no">All</span>)
<span class="no">expectedNumbers</span> <span class="kw">&lt;-</span> <span class="no">expectedProportions</span> * <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>))

<span class="no">mp</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>),
              <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Observed and expected numbers"</span>,
              <span class="kw">ylim</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>, <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span>(<span class="no">expectedNumbers</span>)),
              <span class="kw">las</span> <span class="kw">=</span> <span class="fl">2</span>)

<span class="fu"><a href="https://rdrr.io/r/graphics/lines.html">lines</a></span>(<span class="no">mp</span>, <span class="no">expectedNumbers</span>, <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">2</span>, <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">2</span>)</pre></body></html></div>
<p><img src="as_files/figure-html/as37-1.png" width="700"></p>
<p>The observed and expected numbers are similar to each other. The lumpiness in the observed numbers is due to age heaping. See Figure ASA04.</p>
<p>Formal testing can be performed:</p>
<div class="sourceCode" id="cb74"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>),
           <span class="kw">p</span> <span class="kw">=</span> <span class="no">expectedProportions</span>)</pre></body></html></div>
<p>This gives:</p>
<pre><code>#&gt; Warning in chisq.test(table(svy$ageGroup), p = expectedProportions): Chi-squared
#&gt; approximation may be incorrect
#&gt; 
#&gt;  Chi-squared test for given probabilities
#&gt; 
#&gt; data:  table(svy$ageGroup)
#&gt; X-squared = 248.41, df = 18, p-value &lt; 2.2e-16</code></pre>
<p>The warning is due to small expected numbers (i.e. n &lt; 5) in the older age-groups. R provides a more robust “Monte Carlo” test:</p>
<div class="sourceCode" id="cb76"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">ageGroup</span>),
           <span class="kw">p</span> <span class="kw">=</span> <span class="no">expectedProportions</span>,
           <span class="kw">simulate.p.value</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html></div>
<p>This may take a few seconds to compute and yields:</p>
<pre><code>#&gt; 
#&gt;  Chi-squared test for given probabilities with simulated p-value (based
#&gt;  on 2000 replicates)
#&gt; 
#&gt; data:  table(svy$ageGroup)
#&gt; X-squared = 248.41, df = NA, p-value = 0.0004998</code></pre>
<p>The test results need to be interpreted with caution. The sample size (<span class="math inline">\(n = 8736\)</span>) is large in this example. This means that small differences, which may be due to age heaping, become statistically significant. This test cannot be considered to be good evidence that the age-structure of the sample differs from the expected age-structure of the population. We also need to examine the sex ratio of the sample. A sex ratio test can be performed using the <code><a href="../reference/sexRatioTest.html">sexRatioTest()</a></code> function from the NiPN data quality toolkit and the sex ratio observed in the census data:</p>
<div class="sourceCode" id="cb78"><html><body><pre class="r"><span class="no">censusM</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">ref</span>$<span class="no">Males</span>)
<span class="no">censusF</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">ref</span>$<span class="no">Females</span>)

<span class="fu"><a href="../reference/sexRatioTest.html">sexRatioTest</a></span>(<span class="no">svy</span>$<span class="no">sex</span>,
             <span class="kw">codes</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>, <span class="fl">2</span>),
             <span class="kw">pop</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="no">censusM</span>, <span class="no">censusF</span>))</pre></body></html></div>
<p>This yields:</p>
<pre><code>#&gt; 
#&gt;  Sex Ratio Test
#&gt; 
#&gt; Expected proportion male = 0.4988
#&gt; Observed proportion male = 0.4914
#&gt; X-squared = 1.8770, p = 0.1707</code></pre>
<p>There is no evidence that the sex ratio in the sample differs much from the expected sex ratio in the population.</p>
<p>The techniques outlined in this section are illustrative. This is because many surveys, other than nutritional anthropometry surveys in young children, are not standardised. A survey may sample only women of child-bearing age. The sample may be restricted to women aged between 15 and 45 years.</p>
<p>In this case the age-structure can be examined using the techniques outlined above but it would make no sense to examine the sex ratio. Care should be taken when examining data from surveys that may have deliberately oversampled specific age-groups.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Mark Myatt, Ernest Guevarra.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
