<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Digit preference • nipnTK</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/sandstone/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Digit preference">
<meta property="og:description" content="nipnTK">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-155098215-2"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-155098215-2');
</script>
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">nipnTK</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/nipnTK.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/rl.html">Check ranges and legal values</a>
    </li>
    <li>
      <a href="../articles/sp.html">Identify outliers using scatterplots</a>
    </li>
    <li>
      <a href="../articles/flagging.html">Identify outliers using flags</a>
    </li>
    <li>
      <a href="../articles/ad.html">Assess distributions of variables and indices</a>
    </li>
    <li>
      <a href="../articles/dp.html">Assess digit preference</a>
    </li>
    <li>
      <a href="../articles/ah.html">Assess age heaping</a>
    </li>
    <li>
      <a href="../articles/sr.html">Assess sex ratio</a>
    </li>
    <li>
      <a href="../articles/as.html">Assess age and sex distributions</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://twitter.com/ernestguevarra">
    <span class="fab fa fab fa-twitter fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/ernestguevarra/">
    <span class="fab fa fab fa-linkedin fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/nutriverse/nipnTK/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="dp_files/accessible-code-block-0.0.1/empty-anchor.js"></script><script src="dp_files/kePrint-0.0.1/kePrint.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Digit preference</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/nutriverse/nipnTK/blob/master/vignettes/dp.Rmd"><code>vignettes/dp.Rmd</code></a></small>
      <div class="hidden name"><code>dp.Rmd</code></div>

    </div>

    
    
<div id="digit-preference-in-anthropometric-measurements" class="section level2">
<h2 class="hasAnchor">
<a href="#digit-preference-in-anthropometric-measurements" class="anchor"></a>Digit preference in anthropometric measurements</h2>
<p>Measurements in nutritional anthropometry surveys are usually taken and recorded to one decimal place. Examples are given in table below.</p>
<table class="table table">
<caption>
Common measurements used in anthropometric surveys
</caption>
<thead><tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Unit
</th>
<th style="text-align:left;">
Precision
</th>
<th style="text-align:left;">
Example
</th>
<th style="text-align:left;">
Notes
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Weight
</td>
<td style="text-align:left;">
kg
</td>
<td style="text-align:left;">
Nearest 0.1 kg
</td>
<td style="text-align:left;">
8.7 kg
</td>
<td style="text-align:left;">
Most surveys use scales with a 0.1 kg precision
</td>
</tr>
<tr>
<td style="text-align:left;">
Height/length
</td>
<td style="text-align:left;">
cm
</td>
<td style="text-align:left;">
Nearest 0.1 cm
</td>
<td style="text-align:left;">
85.3 kg
</td>
<td style="text-align:left;">
Height boards tend to have a 0.1 cm pesion
</td>
</tr>
<tr>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
MUAC
</td>
<td style="text-align:left;">
cm
</td>
<td style="text-align:left;">
Nearest 0.1 cm
</td>
<td style="text-align:left;">
13.7 cm
</td>
<td style="text-align:left;vertical-align: middle !important;" rowspan="2">
MUAC may be measured and recorded in centimetres or millimetres. Sometimes both may be used in the same survey. You will need to check this and recode data
</td>
</tr>
<tr>
<td style="text-align:left;">
mm
</td>
<td style="text-align:left;">
Nearest 0.1 mm
</td>
<td style="text-align:left;">
137 mm
</td>
</tr>
</tbody>
</table>
<p>Digit preference is the observation that the final number in a measurement occurs with a greater frequency that is expected by chance. This can occur because of rounding, the practice of increasing or decreasing the value in a measurement to the nearest whole or half unit, or because data are made up.</p>
<p>When taking and recording measurements in the field it is common for field staff to round the first value after the decimal point to zero or five. Measurements in whole numbers may also be rounded to the nearest decade (e.g. 137 mm may be rounded to 140 mm) or half-decade (e.g. 137 mm may be rounded to 135 mm). A small number of rounded measurements is unlikely to affect survey results. A large number of rounded measurements can affect survey results particularly if measurements have been systematically rounded in one direction. This is a form of bias.</p>
<p>Fictitious data often shows digit preference with (e.g.) ”2” and “6” appearing as final digits much more frequently than expected. This happens because, without using a computer, a large quantity of random data is very much harder to fake than merely random-looking data.</p>
<p>If there were little or no digit preference in anthropometric data then we would expect the final recorded digit of each measurement to occur with approximately equal frequency. We can check if digit preference is absent in data by testing whether this is the case.</p>
<p>We will use the R Language for Data Analysis and Graphics to illustrate how this can be done.</p>
</div>
<div id="tabulation-and-visualisation" class="section level2">
<h2 class="hasAnchor">
<a href="#tabulation-and-visualisation" class="anchor"></a>Tabulation and visualisation</h2>
<p>First we will work with some artificial data:</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="fl">0</span>)
<span class="no">finalDigits</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fl">0</span>:<span class="fl">9</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">1000</span>, <span class="kw">replace</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html></div>
<p>The use of <code><a href="https://rdrr.io/r/base/Random.html">set.seed()</a></code> resets the pseudorandom number generator. This ensures that the results shown here are the same as you will get when you follow the example analyses.</p>
<p>You should always examine data before performing any formal tests. A table can be useful:</p>
<div class="sourceCode" id="cb2"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>)</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt; finalDigits
#&gt;   0   1   2   3   4   5   6   7   8   9 
#&gt;  95  80  96 102 106  98 109  95 109 110</code></pre>
<p>We can look at proportions instead of counts:</p>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>))</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt; finalDigits
#&gt;     0     1     2     3     4     5     6     7     8     9 
#&gt; 0.095 0.080 0.096 0.102 0.106 0.098 0.109 0.095 0.109 0.110</code></pre>
<p>If you prefer working with percentages then:</p>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>)) * <span class="fl">100</span></pre></body></html></div>
<p>returns:</p>
<pre><code>#&gt; finalDigits
#&gt;    0    1    2    3    4    5    6    7    8    9 
#&gt;  9.5  8.0  9.6 10.2 10.6  9.8 10.9  9.5 10.9 11.0</code></pre>
<p>Examining data graphically is very useful:</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>), <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Final digit"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Frequency"</span>)</pre></body></html></div>
<p>We can add a line showing our expectation that each final digit should occur about 10% of the time:</p>
<div class="sourceCode" id="cb9"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span>(<span class="kw">h</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>)) / <span class="fl">10</span>, <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">3</span>)</pre></body></html></div>
<p>The resulting plot is shown below.</p>
<p><img src="dp_files/figure-html/unnamed-chunk-11-1.png" width="700"></p>
<p>The tabular and graphical analyses are consistent with there being little or no digit preference in the generated data.</p>
<p>Both analyses agree with the expectation that each final digit should occur about 10% of the time.</p>
<p>All we are seeing is random variation.</p>
<p>We can use a formal test to confirm this:</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>))</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt; 
#&gt;  Chi-squared test for given probabilities
#&gt; 
#&gt; data:  table(finalDigits)
#&gt; X-squared = 7.72, df = 9, p-value = 0.5626</code></pre>
<p>In this example the <em>p-value</em> is not below 0.05 so we accept the <em>null hypothesis</em> that there is no digit preference.</p>
<p>It is important to check that each digit between zero and nine is represented in tables and plots.</p>
<p>Missing digits can indicate strong digit preference.</p>
<p>The NiPN data quality toolkit provides the <code><a href="../reference/fullTable.html">fullTable()</a></code> function. This R language function produces a table that includes cells with zero counts.</p>
<p>As an example we will remove all the values with a final digit equal to 6 from our generated data:</p>
<div class="sourceCode" id="cb12"><html><body><pre class="r"><span class="no">finalDigits</span>[<span class="no">finalDigits</span> <span class="kw">==</span> <span class="fl">6</span>] <span class="kw">&lt;-</span> <span class="fl">NA</span></pre></body></html></div>
<p>and see the effect:</p>
<div class="sourceCode" id="cb13"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>)
<span class="co">#&gt; finalDigits</span>
<span class="co">#&gt;   0   1   2   3   4   5   7   8   9 </span>
<span class="co">#&gt;  95  80  96 102 106  98  95 109 110</span>
<span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>)) * <span class="fl">100</span>
<span class="co">#&gt; finalDigits</span>
<span class="co">#&gt;         0         1         2         3         4         5         7         8 </span>
<span class="co">#&gt; 10.662177  8.978676 10.774411 11.447811 11.896745 10.998878 10.662177 12.233446 </span>
<span class="co">#&gt;         9 </span>
<span class="co">#&gt; 12.345679</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>), <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Final digit"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Frequency"</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span>(<span class="kw">h</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>)) / <span class="fl">10</span>, <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">3</span>)</pre></body></html></div>
<p><img src="dp_files/figure-html/unnamed-chunk-15-1.png" width="70%" style="display: block; margin: auto;"></p>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>))
<span class="co">#&gt; </span>
<span class="co">#&gt;  Chi-squared test for given probabilities</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; data:  table(finalDigits)</span>
<span class="co">#&gt; X-squared = 6.8889, df = 8, p-value = 0.5487</span></pre></body></html></div>
<p>This is a misleading analysis. It is very easy to miss that there are no final digits equal to <strong>6</strong> in the data. The plot is misleading because the final digit <strong>6</strong> is not represented and we assumed that there were ten rather than nine final digits when we calculated the expected frequencies. The Chi-squared test is not correct because it does not account for there being zero cases in which the final digit is equal to <strong>6</strong>.</p>
<p>The <code><a href="../reference/fullTable.html">fullTable()</a></code> function avoids these issues:</p>
<div class="sourceCode" id="cb15"><html><body><pre class="r"><span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>)
<span class="co">#&gt;   0   1   2   3   4   5   6   7   8   9 </span>
<span class="co">#&gt;  95  80  96 102 106  98   0  95 109 110</span>
<span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>)) * <span class="fl">100</span>
<span class="co">#&gt;         0         1         2         3         4         5         6         7 </span>
<span class="co">#&gt; 10.662177  8.978676 10.774411 11.447811 11.896745 10.998878  0.000000 10.662177 </span>
<span class="co">#&gt;         8         9 </span>
<span class="co">#&gt; 12.233446 12.345679</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>), <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Final digit"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Frequency"</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span>(<span class="kw">h</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>)) / <span class="fl">10</span>, <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">3</span>)</pre></body></html></div>
<p><img src="dp_files/figure-html/unnamed-chunk-17-1.png" width="70%" style="display: block; margin: auto;"></p>
<div class="sourceCode" id="cb16"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(<span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>))
<span class="co">#&gt; </span>
<span class="co">#&gt;  Chi-squared test for given probabilities</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; data:  fullTable(finalDigits)</span>
<span class="co">#&gt; X-squared = 106.65, df = 9, p-value &lt; 2.2e-16</span></pre></body></html></div>
<p>The Chi-squared test (incorrectly) calculated without the zero cell:</p>
<pre><code>#&gt; 
#&gt;  Chi-squared test for given probabilities
#&gt; 
#&gt; data:  table(finalDigits)
#&gt; X-squared = 6.8889, df = 8, p-value = 0.5487</code></pre>
<p>indicates that there is no problem with the data.</p>
<p>The chi-square test (correctly) calculated with the zero cell:</p>
<pre><code>#&gt; 
#&gt;  Chi-squared test for given probabilities
#&gt; 
#&gt; data:  fullTable(finalDigits)
#&gt; X-squared = 106.65, df = 9, p-value &lt; 2.2e-16</code></pre>
<p>indicates that there is a problem with the data.</p>
<p>Note that we use <code>sum(fullTable(finalDigits)) / 10</code> (i.e. we divide by ten) because we know that there should be ten final digits (i.e. <strong>0, 1, 2, 3, 4, 5, 6, 7, 8, 9</strong>).</p>
<p>There is an issue with using hypothesis test such as the chi-squared test. Test values are strongly influenced by sample size yielding <em>false-negative</em> results when used with small sample sizes and <em>false-positive</em> results when used with large sample sizes.</p>
<p>We can illustrate this by generating some new artificial data with marked digit preference:</p>
<div class="sourceCode" id="cb19"><html><body><pre class="r"><span class="no">finalDigits</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">as.table</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">11</span>, <span class="fl">7</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">7</span>, <span class="fl">11</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">2</span>))
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">finalDigits</span>) <span class="kw">&lt;-</span> <span class="fl">0</span>:<span class="fl">9</span></pre></body></html></div>
<p>This creates a table object containing counts of imaginary final digits.</p>
<p>Looking at this data:</p>
<div class="sourceCode" id="cb20"><html><body><pre class="r"><span class="no">finalDigits</span>
<span class="co">#&gt;  0  1  2  3  4  5  6  7  8  9 </span>
<span class="co">#&gt; 11  7  5  4  7 11  5  4  4  2</span>
<span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="no">finalDigits</span>) * <span class="fl">100</span>
<span class="co">#&gt;         0         1         2         3         4         5         6         7 </span>
<span class="co">#&gt; 18.333333 11.666667  8.333333  6.666667 11.666667 18.333333  8.333333  6.666667 </span>
<span class="co">#&gt;         8         9 </span>
<span class="co">#&gt;  6.666667  3.333333</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="no">finalDigits</span>, <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Final digit"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Frequency"</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span>(<span class="kw">h</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="no">finalDigits</span>) / <span class="fl">10</span>, <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">3</span>)</pre></body></html></div>
<p><img src="dp_files/figure-html/unnamed-chunk-22-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>There is a marked digit preference for zero and five (see figure above). The Chi-squared test:</p>
<div class="sourceCode" id="cb21"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(<span class="no">finalDigits</span>)</pre></body></html></div>
<p>returns:</p>
<pre><code>#&gt; 
#&gt;  Chi-squared test for given probabilities
#&gt; 
#&gt; data:  finalDigits
#&gt; X-squared = 13.667, df = 9, p-value = 0.1347</code></pre>
<p>In this example the Chi-squared test has failed to detect marked digit preference. This is a <em>false negative</em> test result. The failure of the Chi-squared test in this example is due to the small number of observations (i.e. n = 60) used in the analysis.</p>
<p>A tabular and graphical analysis was required to identify the digit preference problem in this example.</p>
<p>We will usually be working with large sample sizes. This can bring the problem of false positives.</p>
<p>We will generate some data:</p>
<div class="sourceCode" id="cb23"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="fl">3</span>)
<span class="no">finalDigits</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="fl">0</span>:<span class="fl">9</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">1000</span>, <span class="kw">replace</span> <span class="kw">=</span> <span class="fl">TRUE</span>)</pre></body></html></div>
<p>These data will approximate the properties of a set of true uniformly random numbers.</p>
<p>Any digit preference that we might observe in these data is due solely to chance.</p>
<p>The generated data appear to exhibit some digit preference:</p>
<div class="sourceCode" id="cb24"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">finalDigits</span>)
<span class="co">#&gt; finalDigits</span>
<span class="co">#&gt;   0   1   2   3   4   5   6   7   8   9 </span>
<span class="co">#&gt; 102 104  96  88 103 115  91  86 105 110</span>
<span class="fu"><a href="https://rdrr.io/r/base/proportions.html">prop.table</a></span>(<span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>)) * <span class="fl">100</span>
<span class="co">#&gt;    0    1    2    3    4    5    6    7    8    9 </span>
<span class="co">#&gt; 10.2 10.4  9.6  8.8 10.3 11.5  9.1  8.6 10.5 11.0</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>), <span class="kw">xlab</span> <span class="kw">=</span> <span class="st">"Final digit"</span>, <span class="kw">ylab</span> <span class="kw">=</span> <span class="st">"Frequency"</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span>(<span class="kw">h</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>)) / <span class="fl">10</span>, <span class="kw">lty</span> <span class="kw">=</span> <span class="fl">3</span>)</pre></body></html></div>
<p><img src="dp_files/figure-html/unnamed-chunk-26-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>but this digit preference is not especially marked. The Chi-squared test:</p>
<div class="sourceCode" id="cb25"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span>(<span class="fu"><a href="../reference/fullTable.html">fullTable</a></span>(<span class="no">finalDigits</span>))</pre></body></html></div>
<p>yields:</p>
<pre><code>#&gt; 
#&gt;  Chi-squared test for given probabilities
#&gt; 
#&gt; data:  fullTable(finalDigits)
#&gt; X-squared = 8.16, df = 9, p-value = 0.5181</code></pre>
<p>which suggests significant digit preference.</p>
<p>This is a <em>false positive</em> result because the generated data is constrained to be uniformly random and any digit preference that we observed is due solely to chance.</p>
<p>The failure of the Chi-squared test in this example is due to the test mistaking random variation for digit preference is, in part, due to the use of a large (i.e. <span class="math inline">\(n ~ = ~ 1000\)</span>) number of observations.</p>
<p>It is also important to note that any test with a <em>p &lt; 0.05</em> significance threshold will generate a positive result in 1 in 20 tests with data exhibiting nothing but random variation. All tests with a <em>p &lt; 0.05</em> significance threshold have a 5% false positive rate.</p>
</div>
<div id="avoiding-false-positives-using-the-digit-preference-score" class="section level2">
<h2 class="hasAnchor">
<a href="#avoiding-false-positives-using-the-digit-preference-score" class="anchor"></a>Avoiding false positives using the digit preference score</h2>
<p>The problem of false-positives can be addressed by using a summary measure that takes the effect of sample size into account. A widely used method is the <em>digit preference score</em> (DPS). The DPS was developed by the WHO for the MONICA project:</p>
<p><a href="http://www.thl.fi/publications/monica/bp/bpqa.htm">http://www.thl.fi/publications/monica/bp/bpqa.htm</a></p>
<p>The DPS corrects the Chi-squared statistic (<span class="math inline">\(\chi ^ 2\)</span>) for the sample size (<em>n</em>) and the degrees of freedom (<em>df</em>) of the test:</p>
<p><span class="math display">\[ DPS ~ = ~ 100 ~ \times ~ \sqrt{\frac{\chi ^ 2}{n ~ \times ~ df}} \]</span></p>
<p>This has the effect of “desensitising” the Chi-squared test.</p>
<p>The DPS can be used with anthropometric data from all types surveys and may also be applied to clinical data. A low DPS value indicates little or no digit preference. A high DPS value indicates considerable digit preference.</p>
<p>Guideline values for DPS are shown in table below.</p>
<table class="table table">
<caption>
Guideline thresholds for the DPS
</caption>
<thead><tr>
<th style="text-align:center;">
DPS value
</th>
<th style="text-align:center;">
Interpretation
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;">
0 ≤ DPS &lt; 8
</td>
<td style="text-align:center;">
Excellent
</td>
</tr>
<tr>
<td style="text-align:center;">
8 ≤ DPS &lt; 12
</td>
<td style="text-align:center;">
Good
</td>
</tr>
<tr>
<td style="text-align:center;">
12 ≤ DPS ≤ 20
</td>
<td style="text-align:center;">
Acceptable
</td>
</tr>
<tr>
<td style="text-align:center;">
DPS ≥ 20
</td>
<td style="text-align:center;">
Problematic
</td>
</tr>
</tbody>
</table>
<p>The NiPN data quality toolkit provides the R language function <code><a href="../reference/digitPreference.html">digitPreference()</a></code> for calculating the DPS. Applying this function to the example data:</p>
<div class="sourceCode" id="cb27"><html><body><pre class="r"><span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">finalDigits</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">0</span>)</pre></body></html></div>
<p>yields:</p>
<pre><code>#&gt; 
#&gt;  Digit Preference Score
#&gt; 
#&gt; data:    finalDigits
#&gt; Digit Preference Score (DPS) = 3.01 (Excellent)</code></pre>
<p>which is consistent with there being little or no digit preference in the example data.</p>
<p>The output of the <code><a href="../reference/digitPreference.html">digitPreference()</a></code> function can be saved for later use:</p>
<div class="sourceCode" id="cb29"><html><body><pre class="r"><span class="no">dpsResults</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">finalDigits</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">0</span>)</pre></body></html></div>
<p>The saved output contains the DPS value and frequency tables of the final digits (counts and percentages). These can be accessed using:</p>
<div class="sourceCode" id="cb30"><html><body><pre class="r"><span class="no">dpsResults</span>$<span class="no">dps</span>
<span class="co">#&gt; [1] 3.01</span>
<span class="no">dpsResults</span>$<span class="no">tab</span>
<span class="co">#&gt; finalDigits</span>
<span class="co">#&gt;   0   1   2   3   4   5   6   7   8   9 </span>
<span class="co">#&gt; 102 104  96  88 103 115  91  86 105 110</span>
<span class="no">dpsResults</span>$<span class="no">pct</span>
<span class="co">#&gt; finalDigits</span>
<span class="co">#&gt;    0    1    2    3    4    5    6    7    8    9 </span>
<span class="co">#&gt; 10.2 10.4  9.6  8.8 10.3 11.5  9.1  8.6 10.5 11.0</span>
<span class="no">dpsResults</span>$<span class="no">dpsClass</span>
<span class="co">#&gt; SMART DPS Class </span>
<span class="co">#&gt;     "Excellent"</span></pre></body></html></div>
<p>The saved results may also be plotted:</p>
<div class="sourceCode" id="cb31"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="no">dpsResults</span>, <span class="kw">main</span> <span class="kw">=</span> <span class="st">"finalDigit example data"</span>)</pre></body></html></div>
<p>The resulting plot is shown below.</p>
<p><img src="dp_files/figure-html/unnamed-chunk-35-1.png" width="700"></p>
<p>We will now practice using the <code><a href="../reference/digitPreference.html">digitPreference()</a></code> function on survey data.</p>
<p>We will start by retrieving some survey data:</p>
<div class="sourceCode" id="cb32"><html><body><pre class="r"><span class="no">svy</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span>(<span class="st">"dp.ex01.csv"</span>, <span class="kw">header</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">sep</span> <span class="kw">=</span> <span class="st">","</span>)</pre></body></html></div>
<p>The file <strong>dp.ex01.csv</strong> is a comma-separated-value (CSV) file containing anthropometric data for a single state from a DHS survey of a West African country.</p>
<p>The first few records in this dataset can be seen using:</p>
<div class="sourceCode" id="cb33"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="no">svy</span>)</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt;   psu age sex   wt   ht oedema
#&gt; 1 330  14   1  5.0 65.6      2
#&gt; 2 330  54   2 12.1 99.0      2
#&gt; 3 330  25   1  8.9 59.5      2
#&gt; 4 330  52   1 14.6 98.0      2
#&gt; 5 330  43   1 10.1 99.1      2
#&gt; 6 330   7   1  4.0 58.1      2</code></pre>
<p>The two variables of interest are <strong>wt</strong> (weight) and <strong>ht</strong> (height).</p>
<p>We can examine digit preference in the variable for weight (<strong>wt</strong>) using:</p>
<div class="sourceCode" id="cb35"><html><body><pre class="r"><span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">wt</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">1</span>)</pre></body></html></div>
<p>which returns:</p>
<pre><code>#&gt; 
#&gt;  Digit Preference Score
#&gt; 
#&gt; data:    svy$wt
#&gt; Digit Preference Score (DPS) = 11.86 (Good)</code></pre>
<p>We can plot digit preference using:</p>
<div class="sourceCode" id="cb37"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">wt</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">1</span>), <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Weight"</span>)</pre></body></html></div>
<p>The resulting plot is shown below.</p>
<p><img src="dp_files/figure-html/unnamed-chunk-43-1.png" width="700"></p>
<p>The weight data shows some digit preference and would be classified as “Good” using the classifications shown in the table above.</p>
<p>We can examine digit preference in the variable for height (<strong>ht</strong>) using:</p>
<div class="sourceCode" id="cb38"><html><body><pre class="r"><span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">ht</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">1</span>)
<span class="co">#&gt; </span>
<span class="co">#&gt;  Digit Preference Score</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; data:    svy$ht</span>
<span class="co">#&gt; Digit Preference Score (DPS) = 22.77 (Problematic)</span>
<span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">ht</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">1</span>), <span class="kw">main</span> <span class="kw">=</span> <span class="st">"Height"</span>)</pre></body></html></div>
<p><img src="dp_files/figure-html/unnamed-chunk-44-1.png" width="70%" style="display: block; margin: auto;"></p>
<p>The DPS value (22.77) and the DPS plot (above) show considerable digit preference in the height (<strong>ht</strong>) variable. This would be classified as “Problematic” using the classifications shown in table above.</p>
<p>Note that we specified <code>digits = 1</code> when we used the <code><a href="../reference/digitPreference.html">digitPreference()</a></code> function for the weight and height data in the example DHS data. This is because these variables are measured and recorded to one decimal place.</p>
<p>If we were using the <code><a href="../reference/digitPreference.html">digitPreference()</a></code> function with MUAC data that is measured and recorded as whole numbers (i.e. with no decimal places) then we should specify <code>digits = 0</code>. For example:</p>
<div class="sourceCode" id="cb39"><html><body><pre class="r"><span class="no">svy</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span>(<span class="st">"dp.ex02.csv"</span>, <span class="kw">header</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">sep</span> <span class="kw">=</span> <span class="st">","</span>)</pre></body></html></div>
<p>The file <strong>dp.ex02.csv</strong> is a comma-separated-value (CSV) file containing anthropometric data from a SMART survey in Kabul, Afghanistan.</p>
<p>The first few records in this dataset can be seen using:</p>
<div class="sourceCode" id="cb40"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="no">svy</span>)</pre></body></html></div>
<p>which returns:</p>
<pre><code>#&gt;   psu age sex weight height muac oedema
#&gt; 1   1   6   1    7.3   65.0  146      2
#&gt; 2   1  42   2   12.5   89.5  156      2
#&gt; 3   1  23   1   10.6   78.1  149      2
#&gt; 4   1  18   1   12.8   81.5  160      2
#&gt; 5   1  52   1   12.1   87.3  152      2
#&gt; 6   1  36   2   16.9   93.0  190      2</code></pre>
<p>The variable of interest is <strong>muac</strong> (MUAC). This variable is measured and recorded in whole millimetres.</p>
<p>We can examine digit preference in the MUAC variable using:</p>
<div class="sourceCode" id="cb42"><html><body><pre class="r"><span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">muac</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">0</span>)
<span class="co">#&gt; </span>
<span class="co">#&gt;  Digit Preference Score</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; data:    svy$muac</span>
<span class="co">#&gt; Digit Preference Score (DPS) = 13.08 (Acceptable)</span>
<span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">muac</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">0</span>), <span class="kw">main</span> <span class="kw">=</span> <span class="st">"MUAC"</span>)</pre></body></html></div>
<p><img src="dp_files/figure-html/unnamed-chunk-49-1.png" width="700"></p>
<p>The DPS value (13.08) and the DPS plot (above) show considerable digit preference and would be classified as “Acceptable” using the classifications shown in the table above.</p>
</div>
<div id="some-warnings" class="section level2">
<h2 class="hasAnchor">
<a href="#some-warnings" class="anchor"></a>Some warnings</h2>
<p>The material presented here has assumed that data are recorded with a fixed precision (e.g. one decimal place for weight and height, no decimal places for MUAC). It may be the case that data are recorded with mixed precision. For example, the weights of younger children may be measured using “baby scales” and recorded to the nearest 10 g (i.e. to two decimal places) and the weights of older children measured using “hanging scales” and recorded to the nearest 100 g (i.e. to one decimal place). These sorts of situations can be difficult to handle automatically since (e.g.) 3.1 and 3.10 are the same number and both will be stored in the same way. The easiest approach is to treat the data as two separate datasets when examining digit preference.</p>
<p>Care should be taken to ensure that you do not mistake the limitations of the measuring instrument for digit preference. For example, some designs of MUAC tape can only return measurements with an even number for the final digit. In this case you should never see MUAC measurements with <strong>1, 3, 5, 7,</strong> or <strong>9</strong> as the final digit. This limitation of the instrument would look like digit preference. The <code><a href="../reference/digitPreference.html">digitPreference()</a></code> function can handle this situation.</p>
<p>We will retrieve a dataset:</p>
<div class="sourceCode" id="cb43"><html><body><pre class="r"><span class="no">svy</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span>(<span class="st">"dp.ex03.csv"</span>, <span class="kw">header</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">sep</span> <span class="kw">=</span> <span class="st">","</span>)
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="no">svy</span>)</pre></body></html></div>
<pre><code>#&gt;   age sex weight height muac oedema
#&gt; 1  36   2   12.4   86.9  150      2
#&gt; 2  39   2   10.9   83.5  146      2
#&gt; 3  29   1   11.6   90.6  138      2
#&gt; 4  47   2   14.6   95.5  170      2
#&gt; 5  16   1   10.4   78.9  154      2
#&gt; 6  23   1    8.9   80.8  146      2</code></pre>
<p>The file <strong>dp.ex03.csv</strong> is a comma-separated-value (CSV) file containing anthropometric data for a sample of children living in a refugee camp in a West African country.</p>
<p>MUAC was measured using a “numbers in boxes” design MUAC tape:</p>
<p><img src="../man/figures/oldMUAC.png" width="384"></p>
<p>There can only be even numbers in the final digit when this type of MUAC tape is used.</p>
<p>We should check this:</p>
<div class="sourceCode" id="cb45"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="no">svy</span>$<span class="no">muac</span>)</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt; 
#&gt; 108 114 118 120 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 
#&gt;   1   1   3   3   2   6   5   5  21   8  16  23  20  16  32  26  24  22  16  25 
#&gt; 154 156 158 160 162 164 166 168 170 174 176 178 
#&gt;  16  14  19   8   7   7   9   3  11   2   2   1</code></pre>
<p>There are only even numbers. Any odd number would be a recording error or a data-entry error.</p>
<p>We can examine digit preference in these data using the <code><a href="../reference/digitPreference.html">digitPreference()</a></code> function:</p>
<div class="sourceCode" id="cb47"><html><body><pre class="r"><span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">muac</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">0</span>)</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt; 
#&gt;  Digit Preference Score
#&gt; 
#&gt; data:    svy$muac
#&gt; Digit Preference Score (DPS) = 33.34 (Problematic)</code></pre>
<p>This is misleading because the <code><a href="../reference/digitPreference.html">digitPreference()</a></code> function assumes that all possible final digits (i.e. <strong>0, 1, 2, 3, 4, 5, 6, 7, 8, 9</strong>) should be present. This is not the case in the example data.</p>
<p>We can examine this using:</p>
<div class="sourceCode" id="cb49"><html><body><pre class="r"><span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">muac</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">0</span>)$<span class="no">tab</span></pre></body></html></div>
<p>which returns:</p>
<pre><code>#&gt; svy$muac
#&gt;  0  1  2  3  4  5  6  7  8  9 
#&gt; 75  0 74  0 74  0 77  0 74  0</code></pre>
<p>We can use the <strong>values</strong> parameter of the <code><a href="../reference/digitPreference.html">digitPreference()</a></code> to specify the values that are allowed in the final digit:</p>
<div class="sourceCode" id="cb51"><html><body><pre class="r"><span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span>(<span class="no">svy</span>$<span class="no">muac</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">0</span>, <span class="kw">values</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>, <span class="fl">2</span>, <span class="fl">4</span>, <span class="fl">6</span>, <span class="fl">8</span>))</pre></body></html></div>
<p>This returns:</p>
<pre><code>#&gt; 
#&gt;  Digit Preference Score
#&gt; 
#&gt; data:    svy$muac
#&gt; Digit Preference Score (DPS) = 0.78 (Excellent)</code></pre>
<p>The DPS has moved from 33.34 (“Problematic”) to 0.78 (“Excellent”).</p>
<p>We can tabulate and plot the frequency of final digits in the <strong>muac</strong> variable:</p>
<div class="sourceCode" id="cb53"><html><body><pre class="r"><span class="no">dpsResults</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/digitPreference.html">digitPreference</a></span> (<span class="no">svy</span>$<span class="no">muac</span>, <span class="kw">digits</span> <span class="kw">=</span> <span class="fl">0</span>, <span class="kw">values</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>, <span class="fl">2</span>, <span class="fl">4</span>, <span class="fl">6</span>, <span class="fl">8</span>))
<span class="no">dpsResults</span>$<span class="no">tab</span>
<span class="co">#&gt; svy$muac</span>
<span class="co">#&gt;  0  2  4  6  8 </span>
<span class="co">#&gt; 75 74 74 77 74</span>
<span class="no">dpsResults</span>$<span class="no">pct</span>
<span class="co">#&gt; svy$muac</span>
<span class="co">#&gt;    0    2    4    6    8 </span>
<span class="co">#&gt; 20.1 19.8 19.8 20.6 19.8</span>
<span class="fu"><a href="https://rdrr.io/r/base/plot.html">plot</a></span>(<span class="no">dpsResults</span>)</pre></body></html></div>
<p><img src="dp_files/figure-html/unnamed-chunk-61-1.png" width="700"></p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Mark Myatt, Ernest Guevarra.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
